spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-with-mybatis?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: guava
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.arthursong.demo.entity
#配置mybatis接口及映射文件包为调试模式，方便打印sql语句
logging:
  level:
    com:
      arthursong:
        demo:
          mapper: debug