## 设置tomcat的端口号
server:
  port: 8080
## 设置数据源 ##
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-with-jdbc-template?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
